### ISSUE TITLE
Authentication Errors

### ISSUE THREAD

**Issue by Scags104** [klejejs/ha_keep_notes_sensor#4]
v1.1 from HACS
OS v118.1

Been running for a while and over the last week this has started throwing up authentication errors. Tried regenerating App Password but no changes.  see errors from log

![image](https://user-images.githubusercontent.com/9579616/99813244-6f818980-2b15-11eb-93ec-23bd712df423.png)

**Comment by 3v1n0** [comment]
Yeah, same happens here... Not sure if the underlying gkeepapi component should be updated

**Comment by klejejs** [comment]
I am sorry to inform you, but this repository is being archived due to other similar Home Assistant integrations being maintained. Please feel free to check those out.
